SELECT * FROM ProducerWebSite

-- Single row insert

INSERT INTO ProducerWebSite
	VALUES ('Columbia', 'www.columbia.com')

-- Single row insert (with column names)

SELECT * INTO dbo.GoodCustomers FROM dbo.Customers WHERE CustomerID IS NULL;

INSERT INTO GoodCustomers (CustomerID, CustomerName, Address)
	VALUES (9000, 'Grace Leong', '15 Bukit Purmei Road, Singapore 0904')

-- CREATE TABLE

CREATE TABLE GoodCustomers
(CustomerID nvarchar(4) NOT NULL,
CustomerName nvarchar(50) NOT NULL,
Address nvarchar(65) NOT NULL,
PhoneNumber nvarchar(9),
MemberCategory nvarchar(2) NOT NULL,
PRIMARY KEY (CustomerID, MemberCategory))

SELECT * FROM GoodCustomers

-- Create table with foregin key, random number generated by database
-- Foreign key constraints must have a unique ID

CREATE TABLE ProducerWebsite1
(Producer nvarchar(50) NOT NULL,
WebSite varchar(200) NOT NULL,
PRIMARY KEY (Producer),
FOREIGN KEY (Producer) REFERENCES Producers (Producer))

-- Create table with defined foreign key
-- Easier to reference in the future if you want to drop
-- Can write documentation before running DB script
-- Can re-run scripts for UAT and Production DB generation

CREATE TABLE ProducerWebsite2
(Producer nvarchar(50) NOT NULL,
WebSite varchar(200) NOT NULL,
PRIMARY KEY (Producer),
CONSTRAINT ProducerWS_FK_1 FOREIGN KEY (Producer) REFERENCES Producers (Producer))

-- CREATE INDEX

CREATE INDEX Cust_idx ON Customers(CustomerName);

SELECT * FROM Customers WHERE CustomerName = 'Steven Ou'

-- Primary key is by default a unique index
-- Every index increases the storage space in the database
-- When data is inserted, updated, deleted, index must be recreated.